# Generated by Django 6.0.6 on 2026-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailCodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Not Used'), (1, 'Used'), (2, 'Rejected')], default=0)),
            ],
            options={
                'verbose_name': 'Mail Code Verification',
                'verbose_name_plural': 'Mail Codes Verification',
                'ordering': ('-created_at',),
            },
        ),
    ]
