"""
Django settings for DevSpace project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'REDACTED'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'posts',
    'users',
    'social_django',
    'mail_verifications',
    'turnstile',
]


#Captcha:
TURNSTILE_SITEKEY = '0x4AAAAAADv211_SjHCN0ScO'
TURNSTILE_SECRET = 'REDACTED'


#Oauth2:

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '86621595569-78ujeegrn6fbs1j57ef1tour88i0c631.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET  = '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'

SOCIAL_AUTH_USER_FIELDS = ['username', 'email', 'first_name', 'last_name', 'password']
SOCIAL_AUTH_DISCONNECT_REDIRECT_URL = '/profile/'


SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'users.pipelines.bind_user',
    'social_core.pipeline.user.get_username',

    'social_core.pipeline.social_auth.associate_by_email',

    'users.pipelines.custom_create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    # 'social_core.pipeline.user.user_details',
)


# -------------------

AUTHENTICATION_BACKENDS = ['social_core.backends.google.GoogleOAuth2',
                           'django.contrib.auth.backends.ModelBackend',
                           'users.authentifications.EmailAuthBackend',]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DevSpace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DevSpace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# SOCIAL_AUTH_JSONFIELD_ENABLED = True


AUTH_USER_MODEL = 'users.User'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Devspace_db',
        'USER': 'postgres',
        'PASSWORD': 'REDACTED',
        'HOST': 'localhost',
        'PORT': 5432,

    }
}


#login_urls

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'posts:all_posts'
LOGOUT_REDIRECT_URL = 'users:login'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#email pass:

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'giorgi.serobyan.1@gmail.com'
EMAIL_HOST_PASSWORD = 'REDACTED'
EMAIL_USE_TLS = True

EMAIL_ADMIN = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
